#!/usr/bin/env python3
"""Generate components/display/font6x8.h from the Lexis pixel font.

Lexis (https://github.com/damianvila/font-lexis, CC0) is a fixed 6x8 pixel
font: unitsPerEm=1024, one pixel = 128 units, glyphs are 6 px wide and 8 px
tall (ascent 896 = 7 px of caps, descent -128 = 1 px for descenders).

We extract the *exact* fixed bitmap by sampling the glyph outline at the centre
of each pixel cell with a nonzero-winding point-in-outline test — no rasteriser,
no antialiasing, no size guessing. Output is column-major (one byte per column,
bit0 = top row), matching the SSD1306 canvas.

Run in a container (no host installs):
  docker run --rm -v "$PWD":/project -w /project python:3.12-slim \
    bash -c "pip install -q fonttools && python tools/gen_font.py"
"""
from fontTools.pens.pointInsidePen import PointInsidePen
from fontTools.ttLib import TTFont

FONT_PATH = "assets/fonts/Lexis-Regular.ttf"
FIRST, LAST = 0x20, 0x7E
CELL_W, CELL_H = 6, 8
PIXEL = 128          # font units per pixel
ASCENT = 896         # y of the top edge of the top pixel row

# Cell-centre coordinates in font units (mid-pixel => never on an edge).
COL_X = [PIXEL * c + PIXEL // 2 for c in range(CELL_W)]
ROW_Y = [ASCENT - PIXEL * r - PIXEL // 2 for r in range(CELL_H)]


def glyph_columns(glyph_set, gname):
    cols = []
    for cx in COL_X:
        byte = 0
        for r, cy in enumerate(ROW_Y):
            pen = PointInsidePen(glyph_set, (cx, cy))  # nonzero winding
            glyph_set[gname].draw(pen)
            if pen.getResult():
                byte |= 1 << r
        cols.append(byte)
    return cols


def main():
    font = TTFont(FONT_PATH)
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    notdef = ".notdef" if ".notdef" in font.getGlyphOrder() else None

    lines = [
        "// Generated by tools/gen_font.py from the Lexis pixel font",
        "// (https://github.com/damianvila/font-lexis, CC0). Do not edit by hand.",
        "// 6x8 fixed-cell font, ASCII 0x20..0x7E, column-major (bit0 = top row).",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define FONT_FIRST_CHAR 0x{FIRST:02X}",
        f"#define FONT_LAST_CHAR  0x{LAST:02X}",
        f"#define FONT_WIDTH      {CELL_W}",
        f"#define FONT_HEIGHT     {CELL_H}",
        "",
        f"static const uint8_t font6x8[{LAST - FIRST + 1}][{CELL_W}] = {{",
    ]
    for code in range(FIRST, LAST + 1):
        gname = cmap.get(code, notdef)
        cols = glyph_columns(glyph_set, gname) if gname else [0] * CELL_W
        body = ", ".join(f"0x{c:02X}" for c in cols)
        disp = "backslash" if code == 0x5C else chr(code)
        lines.append(f"    {{ {body} }}, // 0x{code:02X} {disp}")
    lines.append("};")
    lines.append("")

    out = "components/display/font6x8.h"
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {out} ({LAST - FIRST + 1} glyphs from Lexis)")


if __name__ == "__main__":
    main()
